create table public.prezente_santier (
    id_prezenta bigint generated by default as identity primary key,
    id_proiect bigint not null references public.proiecte(id_proiect) on delete cascade,
    id_utilizator bigint not null references public.utilizatori(id_utilizator) on delete cascade,
    data date not null default current_date,
    status text not null default 'prezent' check (status in ('prezent', 'absent', 'concediu', 'medical')),
    ora_intrare time,
    ora_iesire time,
    observatii text,
    inregistrat_de bigint not null references public.utilizatori(id_utilizator),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id_proiect, id_utilizator, data),
    check (ora_iesire is null or ora_intrare is null or ora_iesire >= ora_intrare)
);

create table public.corecturi_santier (
    id_corectura bigint generated by default as identity primary key,
    id_proiect bigint not null references public.proiecte(id_proiect) on delete cascade,
    id_zona bigint references public.zone(id_zona) on delete set null,
    titlu text not null check (length(trim(titlu)) between 1 and 160),
    descriere text not null check (length(trim(descriere)) between 1 and 4000),
    severitate text not null default 'medie' check (severitate in ('scazuta', 'medie', 'ridicata', 'critica')),
    status text not null default 'deschisa' check (status in ('deschisa', 'in_lucru', 'rezolvata', 'respinsa')),
    atribuit_catre bigint references public.utilizatori(id_utilizator) on delete set null,
    creat_de bigint not null references public.utilizatori(id_utilizator),
    termen date,
    rezolvat_la timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.jurnal_santier (
    id_intrare bigint generated by default as identity primary key,
    id_proiect bigint not null references public.proiecte(id_proiect) on delete cascade,
    data date not null default current_date,
    tip text not null check (tip in ('observatie', 'fotografie', 'incident')),
    titlu text not null check (length(trim(titlu)) between 1 and 160),
    descriere text not null check (length(trim(descriere)) between 1 and 4000),
    severitate text check (severitate is null or severitate in ('scazuta', 'medie', 'ridicata', 'critica')),
    cale_fotografie text,
    creat_de bigint not null references public.utilizatori(id_utilizator),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (tip <> 'fotografie' or cale_fotografie is not null)
);

create table public.inchideri_santier (
    id_inchidere bigint generated by default as identity primary key,
    id_proiect bigint not null references public.proiecte(id_proiect) on delete cascade,
    data date not null default current_date,
    rezumat text not null check (length(trim(rezumat)) between 1 and 6000),
    blocaje text,
    plan_urmatoarea_zi text,
    inchis_de bigint not null references public.utilizatori(id_utilizator),
    inchis_la timestamptz not null default now(),
    redeschis_la timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id_proiect, data)
);

create index prezente_santier_project_date_idx
    on public.prezente_santier (id_proiect, data desc);
create index prezente_santier_user_date_idx
    on public.prezente_santier (id_utilizator, data desc);
create index corecturi_santier_project_status_idx
    on public.corecturi_santier (id_proiect, status, created_at desc);
create index corecturi_santier_assignee_open_idx
    on public.corecturi_santier (atribuit_catre, status)
    where atribuit_catre is not null and status in ('deschisa', 'in_lucru');
create index jurnal_santier_project_date_idx
    on public.jurnal_santier (id_proiect, data desc, created_at desc);
create index inchideri_santier_project_date_idx
    on public.inchideri_santier (id_proiect, data desc);

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end
$$;

revoke all on function private.touch_updated_at() from public, anon, authenticated;

create trigger prezente_santier_touch_updated_at
before update on public.prezente_santier
for each row execute function private.touch_updated_at();
create trigger corecturi_santier_touch_updated_at
before update on public.corecturi_santier
for each row execute function private.touch_updated_at();
create trigger jurnal_santier_touch_updated_at
before update on public.jurnal_santier
for each row execute function private.touch_updated_at();
create trigger inchideri_santier_touch_updated_at
before update on public.inchideri_santier
for each row execute function private.touch_updated_at();

alter table public.prezente_santier enable row level security;
alter table public.corecturi_santier enable row level security;
alter table public.jurnal_santier enable row level security;
alter table public.inchideri_santier enable row level security;

create policy "project members can read attendance"
on public.prezente_santier for select to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.view')));
create policy "site managers can create attendance"
on public.prezente_santier for insert to authenticated
with check (
    (select private.can_access_project(id_proiect))
    and (select private.has_permission('site.manage'))
    and (select private.same_company_user(id_utilizator))
    and inregistrat_de = (select private.current_user_id())
);
create policy "site managers can update attendance"
on public.prezente_santier for update to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.manage')))
with check (
    (select private.can_access_project(id_proiect))
    and (select private.same_company_user(id_utilizator))
    and inregistrat_de = (select private.current_user_id())
);
create policy "site managers can delete attendance"
on public.prezente_santier for delete to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.manage')));

create policy "project members can read corrections"
on public.corecturi_santier for select to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.view')));
create policy "site managers can create corrections"
on public.corecturi_santier for insert to authenticated
with check (
    (select private.can_access_project(id_proiect))
    and (select private.has_permission('site.manage'))
    and creat_de = (select private.current_user_id())
    and (atribuit_catre is null or (select private.same_company_user(atribuit_catre)))
);
create policy "site managers can update corrections"
on public.corecturi_santier for update to authenticated
using (
    (select private.can_access_project(id_proiect))
    and (select private.has_permission('site.manage'))
)
with check (
    (select private.can_access_project(id_proiect))
    and (atribuit_catre is null or (select private.same_company_user(atribuit_catre)))
);
create policy "site managers can delete corrections"
on public.corecturi_santier for delete to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.manage')));

create policy "project members can read site journal"
on public.jurnal_santier for select to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.view')));
create policy "project members can create site journal"
on public.jurnal_santier for insert to authenticated
with check (
    (select private.can_access_project(id_proiect))
    and (select private.has_permission('site.view'))
    and creat_de = (select private.current_user_id())
);
create policy "site managers can update site journal"
on public.jurnal_santier for update to authenticated
using (
    (select private.can_access_project(id_proiect))
    and (select private.has_permission('site.manage'))
)
with check ((select private.can_access_project(id_proiect)));
create policy "authors and site managers can delete site journal"
on public.jurnal_santier for delete to authenticated
using (
    (select private.can_access_project(id_proiect))
    and (creat_de = (select private.current_user_id()) or (select private.has_permission('site.manage')))
);

create policy "project members can read daily closures"
on public.inchideri_santier for select to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.view')));
create policy "site managers can close the day"
on public.inchideri_santier for insert to authenticated
with check (
    (select private.can_access_project(id_proiect))
    and (select private.has_permission('site.manage'))
    and inchis_de = (select private.current_user_id())
);
create policy "site managers can update daily closures"
on public.inchideri_santier for update to authenticated
using ((select private.can_access_project(id_proiect)) and (select private.has_permission('site.manage')))
with check ((select private.can_access_project(id_proiect)));

revoke all on public.prezente_santier, public.corecturi_santier,
    public.jurnal_santier, public.inchideri_santier from anon, authenticated;
grant select, insert, update, delete on public.prezente_santier to authenticated;
grant select, insert, update, delete on public.corecturi_santier to authenticated;
grant select, insert, update, delete on public.jurnal_santier to authenticated;
grant select, insert, update on public.inchideri_santier to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'santier-fotografii',
    'santier-fotografii',
    false,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "project members can view site photos"
on storage.objects for select to authenticated
using (
    bucket_id = 'santier-fotografii'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and (select private.can_access_project(((storage.foldername(name))[1])::bigint))
    and (select private.has_permission('site.view'))
);
create policy "project members can upload site photos"
on storage.objects for insert to authenticated
with check (
    bucket_id = 'santier-fotografii'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and (select private.can_access_project(((storage.foldername(name))[1])::bigint))
    and (select private.has_permission('site.view'))
    and owner_id = (select auth.uid()::text)
);
create policy "photo owners and site managers can delete site photos"
on storage.objects for delete to authenticated
using (
    bucket_id = 'santier-fotografii'
    and (storage.foldername(name))[1] ~ '^[0-9]+$'
    and (select private.can_access_project(((storage.foldername(name))[1])::bigint))
    and (owner_id = (select auth.uid()::text) or (select private.has_permission('site.manage')))
);

-- A closed day is immutable even if a client bypasses the application UI.
create policy "closed days reject attendance inserts"
on public.prezente_santier as restrictive for insert to authenticated
with check (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = prezente_santier.id_proiect and i.data = prezente_santier.data
));
create policy "closed days reject attendance updates"
on public.prezente_santier as restrictive for update to authenticated
using (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = prezente_santier.id_proiect and i.data = prezente_santier.data
))
with check (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = prezente_santier.id_proiect and i.data = prezente_santier.data
));
create policy "closed days reject attendance deletes"
on public.prezente_santier as restrictive for delete to authenticated
using (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = prezente_santier.id_proiect and i.data = prezente_santier.data
));

create policy "closed days reject journal inserts"
on public.jurnal_santier as restrictive for insert to authenticated
with check (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = jurnal_santier.id_proiect and i.data = jurnal_santier.data
));
create policy "closed days reject journal updates"
on public.jurnal_santier as restrictive for update to authenticated
using (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = jurnal_santier.id_proiect and i.data = jurnal_santier.data
))
with check (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = jurnal_santier.id_proiect and i.data = jurnal_santier.data
));
create policy "closed days reject journal deletes"
on public.jurnal_santier as restrictive for delete to authenticated
using (not exists (
    select 1 from public.inchideri_santier i
    where i.id_proiect = jurnal_santier.id_proiect and i.data = jurnal_santier.data
));

create policy "closed days reject time entry inserts"
on public.istoric_pontari as restrictive for insert to authenticated
with check (not exists (
    select 1
    from public.zone z
    join public.inchideri_santier i on i.id_proiect = z.id_proiect
    where z.id_zona = istoric_pontari.id_zona and i.data = istoric_pontari.data_pontarii
));
create policy "closed days reject time entry updates"
on public.istoric_pontari as restrictive for update to authenticated
using (not exists (
    select 1
    from public.zone z
    join public.inchideri_santier i on i.id_proiect = z.id_proiect
    where z.id_zona = istoric_pontari.id_zona and i.data = istoric_pontari.data_pontarii
))
with check (not exists (
    select 1
    from public.zone z
    join public.inchideri_santier i on i.id_proiect = z.id_proiect
    where z.id_zona = istoric_pontari.id_zona and i.data = istoric_pontari.data_pontarii
));
create policy "closed days reject time entry deletes"
on public.istoric_pontari as restrictive for delete to authenticated
using (not exists (
    select 1
    from public.zone z
    join public.inchideri_santier i on i.id_proiect = z.id_proiect
    where z.id_zona = istoric_pontari.id_zona and i.data = istoric_pontari.data_pontarii
));
